#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Generated by scripts/cli_schema.py. Edit the argparse definition instead.
tm_schema_help() {
    case ${1:-} in
        '') cat <<'TM_SCHEMA_HELP_ROOT'
usage: termux-muscle [-h] [--root DIR] [--prefix DIR] [--version] COMMAND ...

Install, run and maintain Claude Code on Termux.

positional arguments:
  COMMAND
    help         Show the manager command overview.
    install      Install the pinned Claude Code runtime and set up claude on
                 PATH.
    run          Run Claude Code and forward all following arguments
                 unchanged.
    update       Validate a runtime candidate before changing the active
                 release.
    rollback     Restore the previous validated runtime release.
    repair       Rebuild the current runtime from verified original artifacts.
    versions     Show current, previous and retained runtime releases.
    doctor       Check local installation health without model requests.
    migration    Report read-only settings and path migration advisories.
    test         Write a sanitized local device report; no uploads.
    link         Own a Claude command entry with restoration evidence.
    cleanup      Remove inactive releases while protecting active sessions.
    self-update  Install a newer Termux Muscle manager release.
    uninstall    Remove owned files and restore eligible original entries.

options:
  -h, --help     show this help message and exit
  --root DIR     managed installation root
  --prefix DIR   native Termux package prefix
  --version      print manager version

Install/update: --claude-version X.Y.Z|latest with --allow-unverified requests
an upstream release beyond the project pin. Repair/update --offline uses
verified cached artifacts. Test --model permits an authenticated model
request. Self-update exits 0 when installed, 2 when current, 3 for an older
target, and 1 on failure. Use --force to reinstall or compatibly downgrade. By
default, self-update shows one progress dot per completed test program;
--verbose streams the full log and --json includes its full bounded
transcript. This independent OAS project is not affiliated with or authorized
by Anthropic. Full manual: man termux-muscle.
TM_SCHEMA_HELP_ROOT
            ;;
        help) cat <<'TM_SCHEMA_HELP_HELP'
usage: termux-muscle help [-h] [--root DIR] [--prefix DIR]

Show the manager command overview.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
TM_SCHEMA_HELP_HELP
            ;;
        install) cat <<'TM_SCHEMA_HELP_INSTALL'
usage: termux-muscle install [-h] [--root DIR] [--prefix DIR]
                             [--claude-version X.Y.Z|latest]
                             [--allow-unverified] [--offline] [--no-link]

Install the pinned Claude Code runtime and set up claude on PATH.

options:
  -h, --help            show this help message and exit
  --root DIR            managed installation root
  --prefix DIR          native Termux package prefix
  --claude-version X.Y.Z|latest
                        select an upstream version
  --allow-unverified    permit a version beyond the project pin
  --offline             use verified cached archives
  --no-link             preserve existing Claude command entries
TM_SCHEMA_HELP_INSTALL
            ;;
        run) cat <<'TM_SCHEMA_HELP_RUN'
usage: termux-muscle run [--] CLAUDE_ARGUMENTS...

Run Claude Code and forward all following arguments unchanged.

positional arguments:
  CLAUDE_ARGUMENTS
TM_SCHEMA_HELP_RUN
            ;;
        update) cat <<'TM_SCHEMA_HELP_UPDATE'
usage: termux-muscle update [-h] [--root DIR] [--prefix DIR]
                            [--claude-version X.Y.Z|latest]
                            [--allow-unverified] [--offline]

Validate a runtime candidate before changing the active release.

options:
  -h, --help            show this help message and exit
  --root DIR            managed installation root
  --prefix DIR          native Termux package prefix
  --claude-version X.Y.Z|latest
                        select an upstream version
  --allow-unverified    permit a version beyond the project pin
  --offline             use verified cached archives
TM_SCHEMA_HELP_UPDATE
            ;;
        rollback) cat <<'TM_SCHEMA_HELP_ROLLBACK'
usage: termux-muscle rollback [-h] [--root DIR] [--prefix DIR]

Restore the previous validated runtime release.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
TM_SCHEMA_HELP_ROLLBACK
            ;;
        repair) cat <<'TM_SCHEMA_HELP_REPAIR'
usage: termux-muscle repair [-h] [--root DIR] [--prefix DIR] [--offline]

Rebuild the current runtime from verified original artifacts.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
  --offline     use verified cached archives
TM_SCHEMA_HELP_REPAIR
            ;;
        versions) cat <<'TM_SCHEMA_HELP_VERSIONS'
usage: termux-muscle versions [-h] [--root DIR] [--prefix DIR] [--json]

Show current, previous and retained runtime releases.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
  --json        print machine readable state
TM_SCHEMA_HELP_VERSIONS
            ;;
        doctor) cat <<'TM_SCHEMA_HELP_DOCTOR'
usage: termux-muscle doctor [-h] [--root DIR] [--prefix DIR] [--output FILE]

Check local installation health without model requests.

options:
  -h, --help     show this help message and exit
  --root DIR     managed installation root
  --prefix DIR   native Termux package prefix
  --output FILE  write a sanitized local report
TM_SCHEMA_HELP_DOCTOR
            ;;
        migration) cat <<'TM_SCHEMA_HELP_MIGRATION'
usage: termux-muscle migration [-h] [--root DIR] [--prefix DIR]

Report read-only settings and path migration advisories.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
TM_SCHEMA_HELP_MIGRATION
            ;;
        test) cat <<'TM_SCHEMA_HELP_TEST'
usage: termux-muscle test [-h] [--root DIR] [--prefix DIR] [--output FILE]
                          [--model MODEL_ID]

Write a sanitized local device report; no uploads.

options:
  -h, --help        show this help message and exit
  --root DIR        managed installation root
  --prefix DIR      native Termux package prefix
  --output FILE     write a new local report
  --model MODEL_ID  permit an authenticated model request
TM_SCHEMA_HELP_TEST
            ;;
        link) cat <<'TM_SCHEMA_HELP_LINK'
usage: termux-muscle link [-h] [--root DIR] [--prefix DIR] [--replace]
                          [--path PATH]

Own a Claude command entry with restoration evidence.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
  --replace     back up and replace a foreign entry
  --path PATH   choose the command entry
TM_SCHEMA_HELP_LINK
            ;;
        cleanup) cat <<'TM_SCHEMA_HELP_CLEANUP'
usage: termux-muscle cleanup [-h] [--root DIR] [--prefix DIR] [--keep N]
                             [--dry-run]

Remove inactive releases while protecting active sessions.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
  --keep N      retention count
  --dry-run     report without deleting
TM_SCHEMA_HELP_CLEANUP
            ;;
        self-update) cat <<'TM_SCHEMA_HELP_SELF_UPDATE'
usage: termux-muscle self-update [-h] [--root DIR] [--prefix DIR]
                                 [--version X.Y.Z] [-f] [-V] [--json]

Install a newer Termux Muscle manager release.

options:
  -h, --help       show this help message and exit
  --root DIR       managed installation root
  --prefix DIR     native Termux package prefix
  --version X.Y.Z  select an exact manager release
  -f, --force      permit compatible reinstall or downgrade
  -V, --verbose    stream the full build and test log
  --json           print a versioned result with full transcript
TM_SCHEMA_HELP_SELF_UPDATE
            ;;
        uninstall) cat <<'TM_SCHEMA_HELP_UNINSTALL'
usage: termux-muscle uninstall [-h] [--root DIR] [--prefix DIR]

Remove owned files and restore eligible original entries.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
TM_SCHEMA_HELP_UNINSTALL
            ;;
        *) tm_error usage 'Unknown command help target.' ;;
    esac
}

tm_schema_validate() {
    local command=$1; shift
    while (($#)); do
        case $command/$1 in
            help/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            help/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            install/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            install/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            install/--claude-version) (($# > 1)) || tm_error usage '--claude-version needs a value.'; shift 2 ;;
            install/--allow-unverified) shift ;;
            install/--offline) shift ;;
            install/--no-link) shift ;;
            update/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            update/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            update/--claude-version) (($# > 1)) || tm_error usage '--claude-version needs a value.'; shift 2 ;;
            update/--allow-unverified) shift ;;
            update/--offline) shift ;;
            rollback/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            rollback/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            repair/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            repair/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            repair/--offline) shift ;;
            versions/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            versions/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            versions/--json) shift ;;
            doctor/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            doctor/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            doctor/--output) (($# > 1)) || tm_error usage '--output needs a value.'; shift 2 ;;
            migration/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            migration/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            test/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            test/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            test/--output) (($# > 1)) || tm_error usage '--output needs a value.'; shift 2 ;;
            test/--model) (($# > 1)) || tm_error usage '--model needs a value.'; shift 2 ;;
            link/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            link/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            link/--replace) shift ;;
            link/--path) (($# > 1)) || tm_error usage '--path needs a value.'; shift 2 ;;
            cleanup/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            cleanup/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            cleanup/--keep) (($# > 1)) || tm_error usage '--keep needs a value.'; shift 2 ;;
            cleanup/--dry-run) shift ;;
            self-update/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            self-update/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            self-update/--version) (($# > 1)) || tm_error usage '--version needs a value.'; shift 2 ;;
            self-update/-f|self-update/--force) shift ;;
            self-update/-V|self-update/--verbose) shift ;;
            self-update/--json) shift ;;
            uninstall/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            uninstall/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            */--help|*/-h) tm_schema_help "$command"; exit 0 ;;
            *) tm_error usage "Unknown $command option or argument: $1" ;;
        esac
    done
}
