#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Generated by scripts/cli_schema.py. Edit the argparse definition instead.
tm_schema_help() {
    case ${1:-} in
        '') cat <<'TM_SCHEMA_HELP_ROOT'
usage: termux-muscle [--root DIR] [--prefix DIR] <command> [options]
       termux-muscle --version | --help

Install, run and maintain Claude Code on Termux.

Claude Code:
  install      Install the pinned Claude Code release and put claude on PATH
  run          Run Claude Code, passing all following arguments through
  update       Validate a newer Claude Code release, then switch to it
  rollback     Switch back to the previous validated release
  repair       Rebuild the active release from verified original artifacts
  versions     List installed releases; --available lists installable ones
  cleanup      Remove inactive releases, protecting running sessions
  link         Take over the claude command, recording how to restore it

Termux Muscle:
  self-update  Upgrade Termux Muscle itself (not Claude Code)
  uninstall    Remove Termux Muscle and restore the original claude command
  help         Show this overview, or 'help <command>' for one command

Troubleshooting (checks the device, Termux Muscle and Claude Code together;
read-only, nothing is uploaded):
  doctor       Check that the device, the claude launcher and the active
               Claude Code release all work, without contacting Anthropic
  test         Run the doctor checks and save a sanitized device report;
               --model also makes one real model request
  migration    Find leftover pre-Termux-Muscle workarounds in Claude Code's
               settings, plugin paths and PATH

Global options:
  --root DIR     managed installation root
                 (default: ~/.local/share/termux-muscle)
  --prefix DIR   Termux package prefix (default: $PREFIX)
  --version      print Termux Muscle and active Claude Code versions
  -h, --help     show this help

Common tasks:
  termux-muscle versions --available    what can I install?
  termux-muscle update                  move to the current pinned release
  termux-muscle update --claude-version latest --allow-unverified
                                        try a release beyond the pin
  termux-muscle rollback                undo the last update
  termux-muscle doctor                  something's wrong; start here
  termux-muscle self-update             upgrade the manager

Run 'termux-muscle <command> --help' for its options and exit codes.
Full manual: man termux-muscle

Termux Muscle is an independent open-source project, not affiliated with or
authorized by Anthropic.
TM_SCHEMA_HELP_ROOT
            ;;
        help) cat <<'TM_SCHEMA_HELP_HELP'
usage: termux-muscle help [-h] [--root DIR] [--prefix DIR] [COMMAND]

Show this overview, or 'help <command>' for one command.

positional arguments:
  COMMAND       show help for this command

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
TM_SCHEMA_HELP_HELP
            ;;
        install) cat <<'TM_SCHEMA_HELP_INSTALL'
usage: termux-muscle install [-h] [--root DIR] [--prefix DIR]
                             [--claude-version X.Y.Z|latest]
                             [--allow-unverified] [--offline] [--no-link]

Install the pinned Claude Code release and put claude on PATH.

options:
  -h, --help            show this help message and exit
  --root DIR            managed installation root
  --prefix DIR          native Termux package prefix
  --claude-version X.Y.Z|latest
                        select an upstream version
  --allow-unverified    permit a version beyond the project pin
  --offline             use verified cached archives
  --no-link             preserve existing Claude command entries

Without --claude-version, the project pin is used. Any other version,
including latest, also needs --allow-unverified. Run 'versions --available' to
see installable versions.
TM_SCHEMA_HELP_INSTALL
            ;;
        run) cat <<'TM_SCHEMA_HELP_RUN'
usage: termux-muscle run [--] CLAUDE_ARGUMENTS...

Run Claude Code, passing all following arguments through.

positional arguments:
  CLAUDE_ARGUMENTS
TM_SCHEMA_HELP_RUN
            ;;
        update) cat <<'TM_SCHEMA_HELP_UPDATE'
usage: termux-muscle update [-h] [--root DIR] [--prefix DIR]
                            [--claude-version X.Y.Z|latest]
                            [--allow-unverified] [--offline]

Validate a newer Claude Code release, then switch to it.

options:
  -h, --help            show this help message and exit
  --root DIR            managed installation root
  --prefix DIR          native Termux package prefix
  --claude-version X.Y.Z|latest
                        select an upstream version
  --allow-unverified    permit a version beyond the project pin
  --offline             use verified cached archives

Without --claude-version, the project pin is used. Any other version,
including latest, also needs --allow-unverified. Run 'versions --available' to
see installable versions.
TM_SCHEMA_HELP_UPDATE
            ;;
        rollback) cat <<'TM_SCHEMA_HELP_ROLLBACK'
usage: termux-muscle rollback [-h] [--root DIR] [--prefix DIR]

Switch back to the previous validated release.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
TM_SCHEMA_HELP_ROLLBACK
            ;;
        repair) cat <<'TM_SCHEMA_HELP_REPAIR'
usage: termux-muscle repair [-h] [--root DIR] [--prefix DIR] [--offline]

Rebuild the active release from verified original artifacts.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
  --offline     use verified cached archives
TM_SCHEMA_HELP_REPAIR
            ;;
        versions) cat <<'TM_SCHEMA_HELP_VERSIONS'
usage: termux-muscle versions [-h] [--root DIR] [--prefix DIR] [--available]
                              [--all] [--json]

List installed releases; --available lists installable ones.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
  --available   list installable Claude Code releases
  --all         with --available, list every release
  --json        print machine readable output

--available reads the official npm registry and never installs anything. The
pinned release passed acceptance with this Termux Muscle version, a formerly
pinned release passed with the Termux Muscle releases shown, and every other
version is unverified; install any version other than the pin with update
--claude-version X.Y.Z --allow-unverified.
TM_SCHEMA_HELP_VERSIONS
            ;;
        doctor) cat <<'TM_SCHEMA_HELP_DOCTOR'
usage: termux-muscle doctor [-h] [--root DIR] [--prefix DIR] [--output FILE]

Check that the device, the claude launcher and the active Claude Code release
all work, without contacting Anthropic.

options:
  -h, --help     show this help message and exit
  --root DIR     managed installation root
  --prefix DIR   native Termux package prefix
  --output FILE  write a sanitized local report
TM_SCHEMA_HELP_DOCTOR
            ;;
        migration) cat <<'TM_SCHEMA_HELP_MIGRATION'
usage: termux-muscle migration [-h] [--root DIR] [--prefix DIR]

Find leftover pre-Termux-Muscle workarounds in Claude Code's settings, plugin
paths and PATH.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
TM_SCHEMA_HELP_MIGRATION
            ;;
        test) cat <<'TM_SCHEMA_HELP_TEST'
usage: termux-muscle test [-h] [--root DIR] [--prefix DIR] [--output FILE]
                          [--model MODEL_ID]

Run the doctor checks and save a sanitized device report; --model also makes
one real model request.

options:
  -h, --help        show this help message and exit
  --root DIR        managed installation root
  --prefix DIR      native Termux package prefix
  --output FILE     write a new local report
  --model MODEL_ID  also make one authenticated request with this model
                    (repeatable)
TM_SCHEMA_HELP_TEST
            ;;
        link) cat <<'TM_SCHEMA_HELP_LINK'
usage: termux-muscle link [-h] [--root DIR] [--prefix DIR] [--replace]
                          [--path PATH]

Take over the claude command, recording how to restore it.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
  --replace     back up and replace a foreign entry
  --path PATH   choose the command entry
TM_SCHEMA_HELP_LINK
            ;;
        cleanup) cat <<'TM_SCHEMA_HELP_CLEANUP'
usage: termux-muscle cleanup [-h] [--root DIR] [--prefix DIR] [--keep N]
                             [--dry-run]

Remove inactive releases, protecting running sessions.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
  --keep N      retention count
  --dry-run     report without deleting
TM_SCHEMA_HELP_CLEANUP
            ;;
        self-update) cat <<'TM_SCHEMA_HELP_SELF_UPDATE'
usage: termux-muscle self-update [-h] [--root DIR] [--prefix DIR]
                                 [--version X.Y.Z] [-f] [-V] [--json]

Upgrade Termux Muscle itself (not Claude Code).

options:
  -h, --help       show this help message and exit
  --root DIR       managed installation root
  --prefix DIR     native Termux package prefix
  --version X.Y.Z  install this manager release (default: newest)
  -f, --force      reinstall the same release, or downgrade if compatible
  -V, --verbose    stream the full build and test log
  --json           print a versioned result with the bounded test transcript

By default, one progress dot is shown per completed test program.

exit status:
  0  installed    2  already current    3  target is older    1  failed
TM_SCHEMA_HELP_SELF_UPDATE
            ;;
        uninstall) cat <<'TM_SCHEMA_HELP_UNINSTALL'
usage: termux-muscle uninstall [-h] [--root DIR] [--prefix DIR]

Remove Termux Muscle and restore the original claude command.

options:
  -h, --help    show this help message and exit
  --root DIR    managed installation root
  --prefix DIR  native Termux package prefix
TM_SCHEMA_HELP_UNINSTALL
            ;;
        *) tm_error usage "Unknown command: $1. Run termux-muscle --help." ;;
    esac
}

tm_schema_validate() {
    local command=$1; shift
    while (($#)); do
        case $command/$1 in
            help/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            help/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            install/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            install/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            install/--claude-version) (($# > 1)) || tm_error usage '--claude-version needs a value.'; shift 2 ;;
            install/--allow-unverified) shift ;;
            install/--offline) shift ;;
            install/--no-link) shift ;;
            update/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            update/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            update/--claude-version) (($# > 1)) || tm_error usage '--claude-version needs a value.'; shift 2 ;;
            update/--allow-unverified) shift ;;
            update/--offline) shift ;;
            rollback/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            rollback/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            repair/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            repair/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            repair/--offline) shift ;;
            versions/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            versions/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            versions/--available) shift ;;
            versions/--all) shift ;;
            versions/--json) shift ;;
            doctor/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            doctor/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            doctor/--output) (($# > 1)) || tm_error usage '--output needs a value.'; shift 2 ;;
            migration/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            migration/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            test/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            test/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            test/--output) (($# > 1)) || tm_error usage '--output needs a value.'; shift 2 ;;
            test/--model) (($# > 1)) || tm_error usage '--model needs a value.'; shift 2 ;;
            link/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            link/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            link/--replace) shift ;;
            link/--path) (($# > 1)) || tm_error usage '--path needs a value.'; shift 2 ;;
            cleanup/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            cleanup/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            cleanup/--keep) (($# > 1)) || tm_error usage '--keep needs a value.'; shift 2 ;;
            cleanup/--dry-run) shift ;;
            self-update/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            self-update/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            self-update/--version) (($# > 1)) || tm_error usage '--version needs a value.'; shift 2 ;;
            self-update/-f|self-update/--force) shift ;;
            self-update/-V|self-update/--verbose) shift ;;
            self-update/--json) shift ;;
            uninstall/--root) (($# > 1)) || tm_error usage '--root needs a value.'; shift 2 ;;
            uninstall/--prefix) (($# > 1)) || tm_error usage '--prefix needs a value.'; shift 2 ;;
            */--help|*/-h) tm_schema_help "$command"; exit 0 ;;
            *) tm_error usage "Unknown $command option or argument: $1" ;;
        esac
    done
}
