#!/usr/bin/env bash
# SPDX-License-Identifier: MPL-2.0
# Generated by scripts/cli_schema.py from the argparse command definition.
_termux_muscle_complete() {
    local current=${COMP_WORDS[COMP_CWORD]} previous='' command='' options='' kind='' word i
    local globals='--root --prefix --help --version'
    local commands='help install run update rollback repair versions doctor migration test link cleanup self-update uninstall'
    COMPREPLY=()
    ((COMP_CWORD > 0)) && previous=${COMP_WORDS[COMP_CWORD-1]}
    for ((i=1; i<COMP_CWORD; i++)); do
        word=${COMP_WORDS[i]}
        case $word in
            --root|--prefix) ((i++)); continue ;;
            --) return 0 ;;
        esac
        if [[ -z $command ]]; then
            case $word in
                help|install|run|update|rollback|repair|versions|doctor|migration|test|link|cleanup|self-update|uninstall) command=$word ;;
                -*) ;;
                *) return 0 ;;
            esac
        elif [[ $command == run ]]; then
            return 0
        else
            case $command/$word in
                help/--root) ((i++)); continue ;;
                help/--prefix) ((i++)); continue ;;
                install/--root) ((i++)); continue ;;
                install/--prefix) ((i++)); continue ;;
                install/--claude-version) ((i++)); continue ;;
                update/--root) ((i++)); continue ;;
                update/--prefix) ((i++)); continue ;;
                update/--claude-version) ((i++)); continue ;;
                rollback/--root) ((i++)); continue ;;
                rollback/--prefix) ((i++)); continue ;;
                repair/--root) ((i++)); continue ;;
                repair/--prefix) ((i++)); continue ;;
                versions/--root) ((i++)); continue ;;
                versions/--prefix) ((i++)); continue ;;
                doctor/--root) ((i++)); continue ;;
                doctor/--prefix) ((i++)); continue ;;
                doctor/--output) ((i++)); continue ;;
                migration/--root) ((i++)); continue ;;
                migration/--prefix) ((i++)); continue ;;
                test/--root) ((i++)); continue ;;
                test/--prefix) ((i++)); continue ;;
                test/--output) ((i++)); continue ;;
                test/--model) ((i++)); continue ;;
                link/--root) ((i++)); continue ;;
                link/--prefix) ((i++)); continue ;;
                link/--path) ((i++)); continue ;;
                cleanup/--root) ((i++)); continue ;;
                cleanup/--prefix) ((i++)); continue ;;
                cleanup/--keep) ((i++)); continue ;;
                self-update/--root) ((i++)); continue ;;
                self-update/--prefix) ((i++)); continue ;;
                self-update/--version) ((i++)); continue ;;
                uninstall/--root) ((i++)); continue ;;
                uninstall/--prefix) ((i++)); continue ;;
            esac
        fi
    done
    if [[ $command == run ]]; then return 0; fi
    if [[ $command == help && $current != -* && $previous == help ]]; then
        mapfile -t COMPREPLY < <(compgen -W "$commands" -- "$current")
        return 0
    fi
    case $previous in
        --root|--prefix)
            mapfile -t COMPREPLY < <(compgen -d -- "$current")
            return 0 ;;
    esac
    case $command/$previous in
        help/--root) kind=directory ;;
        help/--prefix) kind=directory ;;
        install/--root) kind=directory ;;
        install/--prefix) kind=directory ;;
        install/--claude-version) kind=selector ;;
        update/--root) kind=directory ;;
        update/--prefix) kind=directory ;;
        update/--claude-version) kind=selector ;;
        rollback/--root) kind=directory ;;
        rollback/--prefix) kind=directory ;;
        repair/--root) kind=directory ;;
        repair/--prefix) kind=directory ;;
        versions/--root) kind=directory ;;
        versions/--prefix) kind=directory ;;
        doctor/--root) kind=directory ;;
        doctor/--prefix) kind=directory ;;
        doctor/--output) kind=file ;;
        migration/--root) kind=directory ;;
        migration/--prefix) kind=directory ;;
        test/--root) kind=directory ;;
        test/--prefix) kind=directory ;;
        test/--output) kind=file ;;
        test/--model) kind=none ;;
        link/--root) kind=directory ;;
        link/--prefix) kind=directory ;;
        link/--path) kind=file ;;
        cleanup/--root) kind=directory ;;
        cleanup/--prefix) kind=directory ;;
        cleanup/--keep) kind=none ;;
        self-update/--root) kind=directory ;;
        self-update/--prefix) kind=directory ;;
        self-update/--version) kind=none ;;
        uninstall/--root) kind=directory ;;
        uninstall/--prefix) kind=directory ;;
    esac
    case $kind in
        directory) mapfile -t COMPREPLY < <(compgen -d -- "$current"); return 0 ;;
        file) mapfile -t COMPREPLY < <(compgen -f -- "$current"); return 0 ;;
        selector) mapfile -t COMPREPLY < <(compgen -W 'latest stable pinned' -- "$current"); return 0 ;;
        none) return 0 ;;
    esac
    if [[ -z $command ]]; then
        mapfile -t COMPREPLY < <(compgen -W "$commands $globals" -- "$current")
    elif [[ $current == -* ]]; then
        case $command in
        help) options='-h --help --root --prefix' ;;
        install) options='-h --help --root --prefix --claude-version --allow-unverified --offline --no-link' ;;
        run) options='' ;;
        update) options='-h --help --root --prefix --claude-version --allow-unverified --offline' ;;
        rollback) options='-h --help --root --prefix' ;;
        repair) options='-h --help --root --prefix --offline' ;;
        versions) options='-h --help --root --prefix --available --all --json' ;;
        doctor) options='-h --help --root --prefix --output' ;;
        migration) options='-h --help --root --prefix' ;;
        test) options='-h --help --root --prefix --output --model' ;;
        link) options='-h --help --root --prefix --replace --path' ;;
        cleanup) options='-h --help --root --prefix --keep --dry-run' ;;
        self-update) options='-h --help --root --prefix --version -f --force -V --verbose --json' ;;
        uninstall) options='-h --help --root --prefix' ;;
        esac
        mapfile -t COMPREPLY < <(compgen -W "$options --root --prefix" -- "$current")
    fi
}
complete -F _termux_muscle_complete termux-muscle
